name = "tote"
version = "1.0.0"

description = "Bags (or multisets) in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "giacomocavalieri", repo = "tote" }

[dependencies]
gleam_stdlib = "~> 0.31"

[dev-dependencies]
gleeunit = "~> 0.10"
prng = "~> 1.0"
